### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by pablanopete** [hutchie25/hello-world#2]
test

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xd092dfeec167dc474ecf21f8a467eff1cefb4ca6](https://etherscan.io/address/0xd092dfeec167dc474ecf21f8a467eff1cefb4ca6)
![QR Code](https://openbounty.status.im/qr/pablanopete/hello-world/bounty/2/af7c55959f73617974efcd44874c2739f0ccdc4b54fe1cdf6da669cba4f1c70c/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
